app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Default:index

results:
    path: /results
    defaults:
        _controller: AppBundle:Default:results

